services:
  db:
    image: pachot/yb-pglike
    environment:
      POSTGRES_DB: 'mydb'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypass'
    ports:
      - 5432:5432
      - 15433:15433
    restart: always
  app:
    image: postgres
    environment:
      PGDATABASE: 'mydb'
      PGUSER: 'myuser'
      PGPASSWORD: 'mypass'
    command: bash -xc ' pgbench -i -h db && pgbench -h db -P 5 -T 60 '
    depends_on:
      db:
        condition: service_healthy
